# Generated by Django 5.2.5 on 2025-08-28 09:11

import candidatures.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200, verbose_name='Poste visé')),
                ('cv', models.FileField(help_text='Formats acceptés: PDF, DOC, DOCX (max 5MB)', upload_to=candidatures.models.candidature_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), candidatures.models.validate_file_size], verbose_name='CV')),
                ('lettre_motivation', models.FileField(blank=True, help_text='Formats acceptés: PDF, DOC, DOCX (max 5MB)', null=True, upload_to=candidatures.models.candidature_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), candidatures.models.validate_file_size], verbose_name='Lettre de motivation')),
                ('message', models.TextField(blank=True, help_text='Message optionnel du candidat', null=True, verbose_name="Message d'accompagnement")),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('en_cours', "En cours d'examen")], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_candidature', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('commentaire_recruteur', models.TextField(blank=True, null=True, verbose_name='Commentaire du recruteur')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('candidat', models.ForeignKey(limit_choices_to={'role': 'candidat'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('recruteur_assigne', models.ForeignKey(blank=True, limit_choices_to={'role': 'recruteur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Recruteur assigné')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_candidature'],
                'unique_together': {('candidat', 'poste')},
            },
        ),
    ]
