# Generated by Django 5.2.5 on 2025-08-29 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees_extractes', models.JSONField(default=dict, help_text="Données brutes extraites par l'IA", verbose_name='Données extraites')),
                ('score_competences', models.FloatField(help_text='Score des compétences (0-100)', verbose_name='Score compétences')),
                ('score_experience', models.FloatField(help_text="Score de l'expérience (0-100)", verbose_name='Score expérience')),
                ('score_formation', models.FloatField(help_text='Score de la formation (0-100)', verbose_name='Score formation')),
                ('score_global', models.FloatField(help_text='Score global de pertinence (0-100)', verbose_name='Score global')),
                ('recommendations', models.TextField(help_text="Recommandations et commentaires de l'IA", verbose_name='Recommandations')),
                ('date_analyse', models.DateTimeField(auto_now_add=True, verbose_name="Date d'analyse")),
                ('modele_utilise', models.CharField(default='BERT', help_text="Nom du modèle IA utilisé pour l'analyse", max_length=100, verbose_name='Modèle IA utilisé')),
                ('version_modele', models.CharField(default='1.0', max_length=50, verbose_name='Version du modèle')),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_ia', to='candidatures.candidature')),
            ],
            options={
                'verbose_name': 'Analyse IA',
                'verbose_name_plural': 'Analyses IA',
                'ordering': ['-date_analyse'],
            },
        ),
    ]
